services:
  filewhisperer:
    image: filewhisperer:latest
    container_name: filewhisperer
    network_mode: "host"
    command: python3 /app/src/server.py -p 50098 -l debug
    runtime: nvidia
    environment:
       TESSDATA_PREFIX: /app/fixtures/tesseract
       FILE_WHISPERER_OUTPUT_DIR: /files
       # Debug备份目录，如果设置则将输入文件保存到此目录用于调试
      #  FILE_WHISPERER_DEBUG_BACKUP_DIR: /tmp/filewhisperer_debug_backup
       # Tree池获取实例的超时时间(秒)
       TREE_POOL_ACQUIRE_TIMEOUT: "10"
       # gRPC线程池大小配置: 负数=CPU核数倍数, 0~1小数=CPU核数百分比, 正整数=具体数量
       GRPC_MAX_WORKERS: "-1"
       # Tree实例池大小配置: 负数=CPU核数倍数, 0~1小数=CPU核数百分比, 正整数=具体数量
       TREE_POOL_SIZE: "-1"
       NVIDIA_VISIBLE_DEVICES: "0"
       NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      #  LD_LIBRARY_PATH: "/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
       CUDA_HOME: "/usr/local/cuda"
       # OCR GPU/CPU 控制配置
       OCR_GPU_ENABLED: "true"
       OCR_GPU_PERCENTAGE: "50"
       # OCR_FORCE_CPU: "false"
    volumes:
      - /mnt/zfs/files:/files
      - /tmp:/tmp
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:54324
        tag: docker.filewhisperer
        fluentd-max-retries: "3"
        fluentd-buffer-limit: "100"
        fluentd-retry-wait: "3s"
        fluentd-async: "true"
    deploy:
      resources:
        limits:
          memory: 60G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]