version: '3.7'
services:
  filewhisperer:
    image: ghcr.io/relaxcloud-cn/filewhisperer:main
    container_name: filewhisperer
    network_mode: "host"
    command: python3 /app/src/server.py -p 50098 -l info
    environment: 
      TESSDATA_PREFIX: /app/fixtures/tesseract
      FILE_WHISPERER_OUTPUT_DIR: /opt/docker/filewhisperer/output
    volumes:
      - ./output:/opt/docker/filewhisperer/output
      - /root/.cache/huggingface/hub:/root/.cache/huggingface/hub
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:54324
        tag: docker.filewhisperer
        fluentd-max-retries: "3"
        fluentd-buffer-limit: "100"
        fluentd-retry-wait: "3s"
        fluentd-async: "true"
    deploy:
      resources:
        limits:
          memory: 20G