services:
  filewhisperer:
    image: filewhisperer:latest
    container_name: filewhisperer
    network_mode: "host"
    command: python3 /app/src/server.py -p 50098 -l debug
    runtime: nvidia
    environment:
       TESSDATA_PREFIX: /app/fixtures/tesseract
       FILE_WHISPERER_OUTPUT_DIR: /files
       TREE_POOL_ACQUIRE_TIMEOUT: "10"
       NVIDIA_VISIBLE_DEVICES: "0"
       NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      #  LD_LIBRARY_PATH: "/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
       CUDA_HOME: "/usr/local/cuda"
    volumes:
      - /mnt/zfs/files:/files
      - /root/.paddlex:/root/.paddlex
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:54324
        tag: docker.filewhisperer
        fluentd-max-retries: "3"
        fluentd-buffer-limit: "100"
        fluentd-retry-wait: "3s"
        fluentd-async: "true"
    deploy:
      resources:
        limits:
          memory: 60G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]