// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_whisper.proto
#ifndef GRPC_file_5fwhisper_2eproto__INCLUDED
#define GRPC_file_5fwhisper_2eproto__INCLUDED

#include "file_whisper.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace whisper {

class Whisper final {
 public:
  static constexpr char const* service_full_name() {
    return "whisper.Whisper";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::whisper::WhisperReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::whisper::WhisperReply>> AsyncWhispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::whisper::WhisperReply>>(AsyncWhisperingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::whisper::WhisperReply>> PrepareAsyncWhispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::whisper::WhisperReply>>(PrepareAsyncWhisperingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::whisper::WhisperReply>* AsyncWhisperingRaw(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::whisper::WhisperReply>* PrepareAsyncWhisperingRaw(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::whisper::WhisperReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>> AsyncWhispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>>(AsyncWhisperingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>> PrepareAsyncWhispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>>(PrepareAsyncWhisperingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response, std::function<void(::grpc::Status)>) override;
      void Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>* AsyncWhisperingRaw(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>* PrepareAsyncWhisperingRaw(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Whispering_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Whispering(::grpc::ServerContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Whispering : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Whispering() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Whispering() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Whispering(::grpc::ServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWhispering(::grpc::ServerContext* context, ::whisper::WhisperRequest* request, ::grpc::ServerAsyncResponseWriter< ::whisper::WhisperReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Whispering<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Whispering : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Whispering() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::whisper::WhisperRequest, ::whisper::WhisperReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response) { return this->Whispering(context, request, response); }));}
    void SetMessageAllocatorFor_Whispering(
        ::grpc::MessageAllocator< ::whisper::WhisperRequest, ::whisper::WhisperReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::whisper::WhisperRequest, ::whisper::WhisperReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Whispering() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Whispering(::grpc::ServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Whispering(
      ::grpc::CallbackServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Whispering<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Whispering : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Whispering() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Whispering() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Whispering(::grpc::ServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Whispering : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Whispering() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Whispering() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Whispering(::grpc::ServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWhispering(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Whispering : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Whispering() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Whispering(context, request, response); }));
    }
    ~WithRawCallbackMethod_Whispering() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Whispering(::grpc::ServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Whispering(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Whispering : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Whispering() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::whisper::WhisperRequest, ::whisper::WhisperReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::whisper::WhisperRequest, ::whisper::WhisperReply>* streamer) {
                       return this->StreamedWhispering(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Whispering() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Whispering(::grpc::ServerContext* /*context*/, const ::whisper::WhisperRequest* /*request*/, ::whisper::WhisperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedWhispering(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::whisper::WhisperRequest,::whisper::WhisperReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Whispering<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Whispering<Service > StreamedService;
};

}  // namespace whisper


#endif  // GRPC_file_5fwhisper_2eproto__INCLUDED
