// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_whisper.proto

#include "file_whisper.pb.h"
#include "file_whisper.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace whisper {

static const char* Whisper_method_names[] = {
  "/whisper.Whisper/Whispering",
};

std::unique_ptr< Whisper::Stub> Whisper::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Whisper::Stub> stub(new Whisper::Stub(channel, options));
  return stub;
}

Whisper::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Whispering_(Whisper_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Whisper::Stub::Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::whisper::WhisperReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::whisper::WhisperRequest, ::whisper::WhisperReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Whispering_, context, request, response);
}

void Whisper::Stub::async::Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::whisper::WhisperRequest, ::whisper::WhisperReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Whispering_, context, request, response, std::move(f));
}

void Whisper::Stub::async::Whispering(::grpc::ClientContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Whispering_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>* Whisper::Stub::PrepareAsyncWhisperingRaw(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::whisper::WhisperReply, ::whisper::WhisperRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Whispering_, context, request);
}

::grpc::ClientAsyncResponseReader< ::whisper::WhisperReply>* Whisper::Stub::AsyncWhisperingRaw(::grpc::ClientContext* context, const ::whisper::WhisperRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWhisperingRaw(context, request, cq);
  result->StartCall();
  return result;
}

Whisper::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Whisper_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Whisper::Service, ::whisper::WhisperRequest, ::whisper::WhisperReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Whisper::Service* service,
             ::grpc::ServerContext* ctx,
             const ::whisper::WhisperRequest* req,
             ::whisper::WhisperReply* resp) {
               return service->Whispering(ctx, req, resp);
             }, this)));
}

Whisper::Service::~Service() {
}

::grpc::Status Whisper::Service::Whispering(::grpc::ServerContext* context, const ::whisper::WhisperRequest* request, ::whisper::WhisperReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace whisper

