#pragma once
#include <map>

namespace whisper_data_type
{
    enum Types
    {
        TEXT_PLAIN,
        COMPRESSED_FILE,
        IMAGE,
        TEXT_HTML,
        OTHER
    };

    const std::map<std::string, Types> Types__1 = {
        // DATA
        {"TEXT", TEXT_PLAIN},

        // FILE
        {"text/plain", TEXT_PLAIN},
        {"text/html", TEXT_HTML},
        {"application/zip", COMPRESSED_FILE},
        {"application/x-rar-compressed", COMPRESSED_FILE},
        {"application/vnd.rar", COMPRESSED_FILE},
        {"application/x-7z-compressed", COMPRESSED_FILE},
        {"application/x-tar", COMPRESSED_FILE},
        {"application/gzip", COMPRESSED_FILE},
        {"application/x-gzip", COMPRESSED_FILE},
        {"application/x-bzip2", COMPRESSED_FILE},
        {"application/x-xz", COMPRESSED_FILE},
        {"image/aces", IMAGE},
        {"image/apng", IMAGE},
        {"image/avci", IMAGE},
        {"image/avcs", IMAGE},
        {"image/avif", IMAGE},
        {"image/bmp", IMAGE},
        {"image/cgm", IMAGE},
        {"image/dicom-rle", IMAGE},
        {"image/dpx", IMAGE},
        {"image/emf", IMAGE},
        {"image/fits", IMAGE},
        {"image/g3fax", IMAGE},
        {"image/gif", IMAGE},
        {"image/heic", IMAGE},
        {"image/heic-sequence", IMAGE},
        {"image/heif", IMAGE},
        {"image/heif-sequence", IMAGE},
        {"image/hej2k", IMAGE},
        {"image/ief", IMAGE},
        {"image/j2c", IMAGE},
        {"image/jls", IMAGE},
        {"image/jp2", IMAGE},
        {"image/jpeg", IMAGE},
        {"image/jph", IMAGE},
        {"image/jphc", IMAGE},
        {"image/jpm", IMAGE},
        {"image/jpx", IMAGE},
        {"image/jxl", IMAGE},
        {"image/jxr", IMAGE},
        {"image/jxrA", IMAGE},
        {"image/jxrS", IMAGE},
        {"image/jxs", IMAGE},
        {"image/jxsc", IMAGE},
        {"image/jxsi", IMAGE},
        {"image/jxss", IMAGE},
        {"image/ktx", IMAGE},
        {"image/ktx2", IMAGE},
        {"image/naplps", IMAGE},
        {"image/png", IMAGE},
        {"image/prs.btif", IMAGE},
        {"image/prs.pti", IMAGE},
        {"image/pwg-raster", IMAGE},
        {"image/svg+xml", IMAGE},
        {"image/t38", IMAGE},
        {"image/tiff", IMAGE},
        {"image/tiff-fx", IMAGE},
        {"image/vnd.adobe.photoshop", IMAGE},
        {"image/vnd.airzip.accelerator.azv", IMAGE},
        {"image/vnd.cns.inf2", IMAGE},
        {"image/vnd.dece.graphic", IMAGE},
        {"image/vnd.djvu", IMAGE},
        {"image/vnd.dwg", IMAGE},
        {"image/vnd.dxf", IMAGE},
        {"image/vnd.dvb.subtitle", IMAGE},
        {"image/vnd.fastbidsheet", IMAGE},
        {"image/vnd.fpx", IMAGE},
        {"image/vnd.fst", IMAGE},
        {"image/vnd.fujixerox.edmics-mmr", IMAGE},
        {"image/vnd.fujixerox.edmics-rlc", IMAGE},
        {"image/vnd.globalgraphics.pgb", IMAGE},
        {"image/vnd.microsoft.icon", IMAGE},
        {"image/vnd.mix", IMAGE},
        {"image/vnd.ms-modi", IMAGE},
        {"image/vnd.mozilla.apng", IMAGE},
        {"image/vnd.net-fpx", IMAGE},
        {"image/vnd.pco.b16", IMAGE},
        {"image/vnd.radiance", IMAGE},
        {"image/vnd.sealed.png", IMAGE},
        {"image/vnd.sealedmedia.softseal.gif", IMAGE},
        {"image/vnd.sealedmedia.softseal.jpg", IMAGE},
        {"image/vnd.svf", IMAGE},
        {"image/vnd.tencent.tap", IMAGE},
        {"image/vnd.valve.source.texture", IMAGE},
        {"image/vnd.wap.wbmp", IMAGE},
        {"image/vnd.xiff", IMAGE},
        {"image/vnd.zbrush.pcx", IMAGE},
        {"image/webp", IMAGE},
        {"image/wmf", IMAGE},
        {"image/x-emf", IMAGE},
        {"image/x-wmf", IMAGE}};
}